// @flow

const INCREASE_REQUESTED = 'INCREASE_REQUESTED';
const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
const FETCH_TODOS_REQUESTED = 'FETCH_TODOS_REQUESTED';
const UPDATE_TODO_REQUESTED = 'UPDATE_TODO_REQUESTED';
const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED';
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
const TOGGLE_MODAL_REQUESTED = 'TOGGLE_MODAL_REQUESTED';
const TOGGLE_DRAWER_REQUESTED = 'TOGGLE_DRAWER_REQUESTED';
const SELECT_TODO_REQUESTED = 'SELECT_TODO_REQUESTED';

export {
  INCREASE_REQUESTED,
  TOGGLE_MODAL_REQUESTED,
  FETCH_TODOS_SUCCESS,
  FETCH_TODOS_REQUESTED,
  UPDATE_TODO_REQUESTED,
  UPDATE_TODO_SUCCESS,
  DELETE_TODO_REQUESTED,
  DELETE_TODO_SUCCESS,
  ADD_TODO_REQUESTED,
  ADD_TODO_SUCCESS,
  TOGGLE_DRAWER_REQUESTED,
  SELECT_TODO_REQUESTED
};
