// @flow

export const INCREASE_REQUESTED: 'INCREASE_REQUESTED' = 'INCREASE_REQUESTED';
export const FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS' = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_REQUESTED: 'FETCH_TODOS_REQUESTED' =
  'FETCH_TODOS_REQUESTED';
export const UPDATE_TODO_REQUESTED: 'UPDATE_TODO_REQUESTED' =
  'UPDATE_TODO_REQUESTED';
export const UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS' = 'UPDATE_TODO_SUCCESS';
export const DELETE_TODO_REQUESTED: 'DELETE_TODO_REQUESTED' =
  'DELETE_TODO_REQUESTED';
export const DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS' = 'DELETE_TODO_SUCCESS';
export const ADD_TODO_REQUESTED: 'ADD_TODO_REQUESTED' = 'ADD_TODO_REQUESTED';
export const ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS' = 'ADD_TODO_SUCCESS';
export const TOGGLE_MODAL_REQUESTED: 'TOGGLE_MODAL_REQUESTED' =
  'TOGGLE_MODAL_REQUESTED';
export const TOGGLE_DRAWER_REQUESTED: 'TOGGLE_DRAWER_REQUESTED' =
  'TOGGLE_DRAWER_REQUESTED';
export const SELECT_TODO_REQUESTED: 'SELECT_TODO_REQUESTED' =
  'SELECT_TODO_REQUESTED';
